---
services:
  api0: &api
    build:
      context: .
    container_name: api0
    hostname: api0
    environment:
      - API_PRIORITY_BACKEND=http://payment-processor-default:8080
      - API_PRIORITY_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "16MB"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.0.166:6543
        tag: api
        mode: "non-blocking"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 60s
      timeout: 10ms
      retries: 5
      start_period: 10s
    networks:
      payment-processor:
      backend:
  api1:
    <<: *api
    container_name: api1
    hostname: api1
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.0.166:6543
        tag: api
        mode: "non-blocking"
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./resources/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api0:
        condition: service_healthy
      api1:
        condition: service_healthy
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"
  db:
    image: postgres:latest
    hostname: db
    container_name: db
    environment:
      - POSTGRES_PASSWORD=MyStrongP@ss
      - POSTGRES_USER=app
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ./resources/scripts/db/init.sql:/docker-entrypoint-initdb.d/0000_init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "85MB"
networks:
  backend:
    name: backend
    driver: bridge
